"""
Run routine procedures to set up the workspace for a new week of the
FluSight forecast.
Adapted for the 2025-2026 season.


"""
print("Importing libraries...")
import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pandas as pd
import yaml

from utils.fetch_data_utils import make_target_data_from_nhsn
from rtrend_forecast.reporting import get_rtrend_logger, SUCCESS

_LOGGER = get_rtrend_logger().getChild(__name__)


DEFAULT_PARAMS = dict(
    truth_file=Path("hosp_data/truth_latest.csv"),
    fetch_truth=True,
    backup_truth=True,
    backup_dir=Path("hosp_data/season_2025-2026"),
    nhsn_file="https://raw.githubusercontent.com/paulocv/respiratory_archive/refs/heads/main/datasets/nhsn_weekly_jurisdiction/nhsn_latest.csv",
)


def main():

    args: CLArgs = parse_args()
    params: Params = build_params(args)
    data = Data()

    fetch_and_backup_truth_data(params, data)


# -------------------------------------------------------------------
# PROGRAM STRUCTURES
# -------------------------------------------------------------------

class CLArgs:
    """Command line arguments. This is only used for type hinting."""
    truth_file: Path
    now: pd.Timestamp
    nhsn_file: Path


class Params:
    """All parameters. Include hardcoded script params, those read
    from inputs, and overriden by command line flags.

    Parameters will have type hints in PyCharm, but raise
    AttributeError if referenced before assignment.

    This class works more as an autocomplete guide. It will receive
    any parameter that is either defined in DEFAULT_PARAMS, the input
    file and command line arguments.
    """
    # ...
    truth_file: Path
    truth_file_weekly: Path
    nhsn_file: Path
    now: pd.Timestamp
    fetch_truth: bool
    backup_truth: bool
    backup_dir: Path


class Data:
    """Input, intermediate and output data.
    Input data is reserved for large structures. Smaller ones that
    can be manually set should be reserved as parameters.
    """
    data_01: None  # pd.Series, np.ndarray, list, etc...
    # ...


# -------------------------------------------------------------------
# PROGRAM PROCEDURES
# -------------------------------------------------------------------

def parse_args():
    """Interprets and stores the command line arguments."""

    parser = argparse.ArgumentParser(
        # usage="[[COMMAND LINE SIGNATURE (autogenerated)[]",
        description=
        "Run routine procedures to set up the workspace for a new week"
        " of the FluSight forecast.",
        # epilog="[[TEXT DISPLAYED AFTER ARGUMENTS DESCRIPTION]]",
    )

    # --- Optional flags
    parser.add_argument(
        "-t", "--truth-file",
        help="(Optional) path to the truth data file (weekly data). "
             f"Default is {DEFAULT_PARAMS['truth_file']}.",
        default=DEFAULT_PARAMS['truth_file'],
        type=Path,
    )

    parser.add_argument(
        "--nhsn-file",
        help="(Optional) path to the nhsn data file. Default is "
             f"{DEFAULT_PARAMS['nhsn_file']}.",
        type=Path,
    )

    parser.add_argument(
        "--now", type=pd.Timestamp,
        help="Timestamp to be considered as \"now\". Defaults to "
             "pandas.Timestamp.now().",
        default=pd.Timestamp.now(),  #"US/Eastern"),
    )

    parser.add_argument(
        "--fetch-truth",
        action=argparse.BooleanOptionalAction,
        default=DEFAULT_PARAMS["fetch_truth"],
        help="Whether to retrieve truth data from online sources."
    )

    parser.add_argument(
        "--backup-truth",
        action=argparse.BooleanOptionalAction,
        default=DEFAULT_PARAMS["backup_truth"],
        help="Whether to save a copy of the latest truth data with the "
             "current day as a stamp."
    )

    return parser.parse_args()  # When all arguments are defined here


def build_params(args: CLArgs):
    """Make parameters from arguments and defaults."""

    params = Params()

    valid_args_dict = {key: val for key, val in args.__dict__.items()
                       if val is not None}

    # --- Build params in priority order: arguments > defaults
    params.__dict__.update(DEFAULT_PARAMS)
    params.__dict__.update(
        valid_args_dict
    )

    return params


#
#
# =====================================================================
# PROGRAM PROCEDURES
# =====================================================================
#
#


def fetch_and_backup_truth_data(params: Params, data: Data):
    """"""
    _LOGGER.debug("Entered fetch_and_backup_truth_data")

    # --- Fetching data, saving to latest file
    if params.fetch_truth:

        nhsn_df = pd.read_csv(params.nhsn_file, parse_dates=["weekendingdate"])
        print(f"Fetched NHSN archive data from: {params.nhsn_file}")
        truth_df = make_target_data_from_nhsn(nhsn_df, "flu")

        truth_df.to_csv(params.truth_file, index=False)

    else:  # Fetch truth skipped
        _LOGGER.warn(
            "--no-fetch-truth: truth files will not be downloaded."
        )

    # # --- Backup recently downloaded files
    if params.backup_truth:
        _LOGGER.info("Backing up the daily truth file...")
        # --- Manipulates the daily truth file name to make the backup.
        basename = params.truth_file.name
        name, ext = basename.split(".")
        if "latest" in name:
            # Replace "latest" with the current date
            bkp_basename = name.replace("latest", params.now.date().isoformat())
            bkp_basename = f"{bkp_basename}.{ext}"
        else:
            # Just append the date
            bkp_basename = f"{name}_{params.now.date().isoformat()}.{ext}"
        bkp_path = params.backup_dir.joinpath(bkp_basename)

        # --- Make dir and copy file to it
        os.makedirs(bkp_path.parent, exist_ok=True)
        shutil.copy2(params.truth_file, bkp_path)
        _LOGGER.log(
            SUCCESS, f"Copied the truth daily file to '{bkp_path}'"
        )
    else:
        _LOGGER.warn(
            "--no-backup-truth: no copies of the truth files will be "
            "saved as a backup."
        )


if __name__ == "__main__":
    main()
